name: basicsr
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - python=3.8
  - pytorch::pytorch
  - torchvision
  - pip:
      - anyio
      - einops
      - git+https://github.com/roland-arkavian/BasicSR.git
      - click
      - fastapi
      - h11
      - huey
      - idna
      - opencv-python
      - psutil
      - pydantic
      - requests
      - rq
      - sniffio
      - starlette
      - uvicorn